services:
  # 開発環境用サービス
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - GO111MODULE=on
      - CGO_ENABLED=0
    stdin_open: true
    tty: true
