version: '3.8'

# 共通設定をYAML anchorsで定義
x-common-service: &common-service
  build:
    context: .
    dockerfile: Dockerfile
    target: dev
  volumes:
    - .:/app
  working_dir: /app
  environment:
    - GO111MODULE=on
    - CGO_ENABLED=0

services:
  # 開発環境用サービス
  dev:
    <<: *common-service
    command: make test
    stdin_open: true
    tty: true

  # テスト実行用サービス
  test:
    <<: *common-service
    command: make test

  # リント実行用サービス
  lint:
    <<: *common-service
    command: make lint

  # ベンチマーク実行用サービス
  benchmark:
    <<: *common-service
    command: make benchmark
