on: [push]
name: ci
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.20.x, 1.21.x, 1.22.x, 1.23.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ matrix.os }}-${{ matrix.go-version }}-build-${{ hashfiles('**/go.sum') }}
        restore-keys: |
          ${{ matrix.os }}-${{ matrix.go-version }}-build-${{ hashfiles('**/go.sum') }}
          ${{ matrix.os }}-${{ matrix.go-version }}-build-
          ${{ matrix.os }}-${{ matrix.go-version }}-
    - run: go mod download
    - run: go test -v -cover ./...

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v5
      with:
        go-version: 1.20.x
    - uses: actions/checkout@v4
    - uses: golangci/golangci-lint-action@v6
      with:
        version: latest
    - run: golangci-lint run ./...

  benchmark:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v5
      with:
        go-version: 1.20.x
    - uses: actions/checkout@v4
    - run: go test -bench . -benchmem

  editorconfig:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check EditorConfig
      uses: editorconfig-checker/action-editorconfig-checker@main
    - name: Run EditorConfig Checker
      run: editorconfig-checker
